# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: kratos

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - make pack

builds:
  -
    id: kratos-sqlite-darwin
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/zzpu/openuser/internal/clihelpers.BuildVersion={{.Tag}} -X github.com/zzpu/openuser/internal/clihelpers.BuildGitHash={{.FullCommit}} -X github.com/zzpu/openuser/internal/clihelpers.BuildTime={{.Date}}
      # - "-extldflags '-static'"
    binary: kratos
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goarch:
      - amd64
    goos:
      - darwin

  -
    id: kratos-sqlite-linux
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/zzpu/openuser/internal/clihelpers.BuildVersion={{.Tag}} -X github.com/zzpu/openuser/internal/clihelpers.BuildGitHash={{.FullCommit}} -X github.com/zzpu/openuser/internal/clihelpers.BuildTime={{.Date}}
    binary: kratos
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
  -
    id: kratos-sqlite-linux-libmusl
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/zzpu/openuser/internal/clihelpers.BuildVersion={{.Tag}} -X github.com/zzpu/openuser/internal/clihelpers.BuildGitHash={{.FullCommit}} -X github.com/zzpu/openuser/internal/clihelpers.BuildTime={{.Date}}
    binary: kratos
    env:
      - CGO_ENABLED=1
      - CC=musl-gcc
    goarch:
      - amd64
    goos:
      - linux
  -
    id: kratos-sqlite-windows
    flags:
      - -tags
      - sqlite
    ldflags:
      - -s -w -X github.com/zzpu/openuser/internal/clihelpers.BuildVersion={{.Tag}} -X github.com/zzpu/openuser/internal/clihelpers.BuildGitHash={{.FullCommit}} -X github.com/zzpu/openuser/internal/clihelpers.BuildTime={{.Date}}
      - "-extldflags '-static'"
    binary: kratos
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goarch:
      - amd64
    goos:
      - windows

  -
    id: kratos
    ldflags:
      - -s -w -X github.com/zzpu/openuser/internal/clihelpers.BuildVersion={{.Tag}} -X github.com/zzpu/openuser/internal/clihelpers.BuildGitHash={{.FullCommit}} -X github.com/zzpu/openuser/internal/clihelpers.BuildTime={{.Date}}
    binary: kratos
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    goos:
      - freebsd
      - linux
      - windows
      - darwin

archives:
  - id: kratos-sqlite
    builds:
      - kratos-sqlite-windows
      - kratos-sqlite-darwin
      - kratos-sqlite-linux
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md
    name_template: "{{ .ProjectName }}_{{ .Version }}-sqlite_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: kratos-sqlite-libmusl
    builds:
      - kratos-sqlite-linux-libmusl
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      -
        goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md
    name_template: "{{ .ProjectName }}_{{ .Version }}-sqlite-libmusl_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

  - id: kratos
    builds:
      - kratos
    replacements:
      darwin: macos
      386: 32bit
      amd64: 64bit
      arm: arm32
    format_overrides:
      - goos: windows
        format: zip
    files:
      - CHANGELOG.md
      - LICENSE
      - README.md
      - SECURITY.md

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - ci skip
      - Merge pull request
      - Merge branch

brews:
  - tap:
      owner: ory
      name: homebrew-kratos
    ids:
    - kratos-sqlite
    homepage:  https://www.ory.sh
    commit_author:
      name: aeneasr
      email: 3372410+aeneasr@users.noreply.github.com

scoop:
  bucket:
    owner: ory
    name: scoop-kratos
  homepage:  https://www.ory.sh
  commit_author:
    name: aeneasr
    email: 3372410+aeneasr@users.noreply.github.com

checksum:
  algorithm: sha256

dockers:
  - dockerfile: .docker/Dockerfile-sqlite
    builds:
      - kratos-sqlite-linux-libmusl
    binaries:
      - kratos
    image_templates:
      - "oryd/kratos:v{{ .Major }}-sqlite"
      - "oryd/kratos:v{{ .Major }}.{{ .Minor }}-sqlite"
      - "oryd/kratos:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}-sqlite"
      - "oryd/kratos:{{.Tag}}-sqlite"
      - "oryd/kratos:latest-sqlite"
  - dockerfile: .docker/Dockerfile
    builds:
      - kratos
    binaries:
      - kratos
    image_templates:
      - "oryd/kratos:v{{ .Major }}"
      - "oryd/kratos:v{{ .Major }}.{{ .Minor }}"
      - "oryd/kratos:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "oryd/kratos:{{.Tag}}"
      - "oryd/kratos:latest"

release:
  prerelease: auto
  name_template: "{{.Tag}}"
  ids:
    - kratos-sqlite
    - kratos-sqlite-libmusl
    - kratos
