version: 2.1

orbs:
  changelog: ory/changelog@0.1.3
  goreleaser: ory/goreleaser@0.1.17
  slack: circleci/slack@3.4.2
  sdk: ory/sdk@0.1.37
  nancy: ory/nancy@0.0.12
  docs: ory/docs@0.0.8
  golangci: ory/golangci@0.0.8

jobs:
  test:
    docker:
      -
        image: circleci/golang:1.15
        environment:
          - GO111MODULE=on
          - TEST_MAILHOG_SMTP=smtp://test:test@127.0.0.1:1025
          - TEST_MAILHOG_API=http://127.0.0.1:8025
          - TEST_SELFSERVICE_OIDC_HYDRA_ADMIN=http://127.0.0.1:4445
          - TEST_SELFSERVICE_OIDC_HYDRA_PUBLIC=http://127.0.0.1:4444
          - TEST_SELFSERVICE_OIDC_HYDRA_INTEGRATION_ADDR=http://127.0.0.1:4499
          - TEST_DATABASE_POSTGRESQL=postgres://test:test@localhost:5432/postgres?sslmode=disable
          - TEST_DATABASE_MYSQL=mysql://root:test@(localhost:3306)/mysql?parseTime=true&multiStatements=true
          - TEST_DATABASE_COCKROACHDB=cockroach://root@localhost:26257/defaultdb?sslmode=disable
      -
        image: mailhog/mailhog:v1.0.0
        command: MailHog -invite-jim -jim-linkspeed-affect=0.25 -jim-reject-auth=0.25 -jim-reject-recipient=0.25 -jim-reject-sender=0.25 -jim-disconnect=0.25 -jim-linkspeed-min=1250 -jim-linkspeed-max=12500
      -
        image: postgres:9.6
        environment:
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=test
          - POSTGRES_DB=postgres
      -
        image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=test
      -
        image: cockroachdb/cockroach:v20.1.1
        command: start --insecure
      -
        image: oryd/hydra:v1.4.10
        environment:
          - DSN=memory
          - URLS_SELF_ISSUER=http://127.0.0.1:4444/
          - URLS_LOGIN=http://127.0.0.1:4499/login
          - URLS_CONSENT=http://127.0.0.1:4499/consent
        command: serve all --dangerous-force-http
    working_directory: /go/src/github.com/zzpu/openuser
    steps:
      - checkout
      - setup_remote_docker
      -
        run: GO111MODULE=off go get github.com/mattn/goveralls github.com/ory/go-acc
      -
        restore_cache:
          keys:
            - go-v1-{{ checksum "go.sum" }}
      -
        run: go mod download
      -
        save_cache:
          key: go-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      -
        run: timeout 15 sh -c 'until nc -z $0 $1; do sleep 1; done' 127.0.0.1 4444
      -
        run: go-acc -o coverage.txt ./... -- -v -failfast -timeout=20m -tags sqlite
      -
        run: test -z "$CIRCLE_PR_NUMBER" && goveralls -service=circle-ci -coverprofile=coverage.txt -repotoken=$COVERALLS_REPO_TOKEN || echo "forks are not allowed to push to coveralls"

  test-e2e:
    parameters:
      flavor:
        type: string
    docker:
      - image: oryd/e2e-env:latest
        environment:
          - GO111MODULE=on
          - TEST_DATABASE_MYSQL=mysql://root:test@(localhost:3306)/mysql?parseTime=true&multiStatements=true
          - TEST_DATABASE_COCKROACHDB=cockroach://root@localhost:26257/defaultdb?sslmode=disable
          - TEST_DATABASE_POSTGRESQL=postgres://test:test@localhost:5432/kratos?sslmode=disable
      - image: postgres:9.6
        environment:
          - POSTGRES_USER=test
          - POSTGRES_PASSWORD=test
          - POSTGRES_DB=kratos
      - image: cockroachdb/cockroach:v20.1.1
        command: start --insecure
      - image: mysql:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=test
      - image: oryd/mailslurper:latest-smtps
    working_directory: /go/src/github.com/zzpu/openuser
    steps:
      - checkout
      # core node_modules cache
      - restore_cache:
          keys:
            - ory-kratos-e2e-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: ory-kratos-e2e-{{ checksum "package-lock.json" }}
          # cache NPM modules and the folder with the Cypress binary
          paths:
            - ~/.npm
            - ~/.cache
      # go modules cache
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: ./test/e2e/run.sh << parameters.flavor >>

  validate:
    docker:
      - image: circleci/golang:1.15-node
        environment:
          GO111MODULE: 'on'
    working_directory: /go/src/github.com/ory/hydra
    steps:
      - checkout
      - golangci/lint
      - docs/check-format

workflows:
  tbr:
    jobs:
      - nancy/test
      -
        validate:
          filters:
            tags:
              only: /.*/
      - test-e2e:
          name: test-e2e-sqlite
          flavor: sqlite
          requires:
            - test
            - nancy/test
            - validate
          filters:
            tags:
              only: /.*/
      - test-e2e:
          name: test-e2e-postgres
          flavor: postgres
          requires:
            - test-e2e-sqlite
          filters:
            tags:
              only: /.*/
      - test-e2e:
          name: test-e2e-mysql
          flavor: mysql
          requires:
            - test-e2e-sqlite
          filters:
            tags:
              only: /.*/
      - test-e2e:
          name: test-e2e-cockroach
          flavor: cockroach
          requires:
            - test-e2e-sqlite
          filters:
            tags:
              only: /.*/
      -
        test:
          filters:
            tags:
              only: /.*/
      - sdk/generate:
          appname: Ory_Kratos
          requires:
            - test
            - test-e2e-sqlite
            - test-e2e-postgres
            - test-e2e-mysql
            - test-e2e-cockroach
            - validate
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /master/
      - docs/cli:
          requires:
            - test
            - test-e2e-sqlite
            - test-e2e-postgres
            - test-e2e-mysql
            - test-e2e-cockroach
            - validate
      - docs/build:
          requires:
            - test
            - test-e2e-sqlite
            - test-e2e-postgres
            - test-e2e-mysql
            - test-e2e-cockroach
            - validate
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      - sdk/release:
          requires:
            - test
            - test-e2e-sqlite
            - test-e2e-postgres
            - test-e2e-mysql
            - test-e2e-cockroach
            - validate
            - sdk/generate
            - goreleaser/release
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - changelog/generate:
          requires:
            - test
            - test-e2e-sqlite
            - test-e2e-postgres
            - test-e2e-mysql
            - test-e2e-cockroach
            - validate
          filters:
            tags:
              only: /.*/
            branches:
              only: master
      -
        goreleaser/test:
          filters:
            tags:
              only: /.*/
      -
        goreleaser/release:
          requires:
            - goreleaser/test
            - test
            - test-e2e-sqlite
            - test-e2e-postgres
            - test-e2e-mysql
            - test-e2e-cockroach
            - validate
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - goreleaser/render-version-schema:
          requires:
            - goreleaser/release
          filters:
            tags:
              only: /.*/
      -
        goreleaser/newsletter-draft:
          chimp-list: f605a41b53
          chimp-segment: 6479477
          requires:
            - goreleaser/release
          filters:
            tags:
              only: /.*/
      -
        slack/approval-notification:
          message: Pending approval
          channel: release-automation
          requires:
            - goreleaser/newsletter-draft
          filters:
            tags:
              only: /.*/
      -
        newsletter-approval:
          type: approval
          requires:
            - goreleaser/newsletter-draft
          filters:
            tags:
              only: /.*/
      -
        goreleaser/newsletter-send:
          chimp-list: f605a41b53
          requires:
            - newsletter-approval
          filters:
            tags:
              only: /.*/
